# 教程

## 导入

In [21]:
import numpy as np
from math import pi

## 基础

### 创建

In [8]:
np.array((1,2,3)) # 从常规的Python元组和列表中创建
np.array([1,2,3])

array([1, 2, 3])

In [14]:
np.array([(1,2,3), (4,5,6)]) # 序列的序列 
np.array([[1,2,3], [4,5,6]])
np.array([([1,2,3], [4,5,6])])

array([[[1, 2, 3],
        [4, 5, 6]]])

In [17]:
np.array([[1,2], [3,4]], dtype=complex) # 创建时指定元素类型

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
# 使用routine
np.zeros((2,3)) # 注意参数是元组
np.ones((2,3,4), dtype=np.int16) # 指定元素的数据类型
np.empty((2,3)) # 元素未初始化

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [23]:
# 数值序列
np.arange(10, 30, 5) # begin, end, step: [begin, end)
np.arange(0, 2, 0.3)

np.linspace(0, 2, 9) # begin, end, number: [begin, end], (number-1)部分
np.linspace(0, 2*pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [27]:
# 全局函数
A = np.arange(3)
B = np.exp(A)
C = np.sqrt(A)
D = np.array([2., -1., 4.])
E = np.add(A, D)

### 基本操作

In [29]:
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3)

A * B # 元素级操作

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [30]:
A.dot(B) # 矩阵乘法
np.dot(A, B) 

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [24]:
a = np.arange(12).reshape(3,4)
a.sum(axis=0) # 沿着行
a.sum(axis=1) # 沿着列

array([ 6, 22, 38])

### 索引, 切片和迭代 

In [39]:
# 一维数组
a = np.arange(10) ** 3

In [33]:
a[2] 

8

In [34]:
a[2:5]

array([ 8, 27, 64])

In [35]:
a[:6:2]

array([ 0,  8, 64])

In [37]:
a[:6:2] = -1000
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [38]:
for i in a:
  print(i ** (1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [40]:
# 多维数组
def f(x, y):
    return 10*x + y
a = np.fromfunction(f, (5,4), dtype=int) # 使用函数创建

In [47]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [41]:
a[2,3]

23

In [42]:
a[0:5, 1] # 元组(0:5, 1)

array([ 1, 11, 21, 31, 41])

In [43]:
a[:, 1] # 元组(0:a.shape[0], 1)

array([ 1, 11, 21, 31, 41])

In [44]:
a[1:3, :] # 元组(1:3, 0:a.shape[1])

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [45]:
a[-1] # 比axis数量少的索引, 元组(-1, 0:a.shape[1])

array([40, 41, 42, 43])

In [46]:
a[-1, ...] # 元组(-1, 0:a.shape[1])

array([40, 41, 42, 43])

In [48]:
# ...的用法
a = np.arange(12).reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
a[1, ...] # 移除第一维外的[]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
a[..., 2] # 移除最后一维外的[]

array([[ 2,  5],
       [ 8, 11]])

In [53]:
# 多维数组遍历
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [54]:
for row in a: #  按第一维度遍历
    print(row, "\n")

[[0 1 2]
 [3 4 5]] 

[[ 6  7  8]
 [ 9 10 11]] 



In [56]:
for e in a.flat: # 遍历每个元素
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11


## 形状操作

## 拷贝和视图


## 索引

## 线性代数


## 一些技巧