# 教程

## 导入

In [1]:
import numpy as np
from math import pi

## 基础

### 创建

In [2]:
np.array((1,2,3)) # 从常规的Python元组和列表中创建
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([(1,2,3), (4,5,6)]) # 序列的序列 
np.array([[1,2,3], [4,5,6]])
np.array([([1,2,3], [4,5,6])])

array([[[1, 2, 3],
        [4, 5, 6]]])

In [4]:
np.array([[1,2], [3,4]], dtype=complex) # 创建时指定元素类型

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [5]:
# 使用routine
np.zeros((2,3)) # 注意参数是元组
np.ones((2,3,4), dtype=np.int16) # 指定元素的数据类型
np.empty((2,3)) # 元素未初始化

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [6]:
# 数值序列
np.arange(10, 30, 5) # begin, end, step: [begin, end)
np.arange(0, 2, 0.3)

np.linspace(0, 2, 9) # begin, end, number: [begin, end], (number-1)部分
np.linspace(0, 2*pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [7]:
# 全局函数
A = np.arange(3)
B = np.exp(A)
C = np.sqrt(A)
D = np.array([2., -1., 4.])
E = np.add(A, D)

### 基本操作

In [8]:
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3)

A * B # 元素级操作

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [9]:
A.dot(B) # 矩阵乘法
np.dot(A, B) 

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [10]:
a = np.arange(12).reshape(3,4)
a.sum(axis=0) # 沿着行
a.sum(axis=1) # 沿着列

array([ 6, 22, 38])

### 索引, 切片和迭代 

In [11]:
# 一维数组
a = np.arange(10) ** 3

In [12]:
a[2] 

8

In [13]:
a[2:5]

array([ 8, 27, 64])

In [14]:
a[:6:2]

array([ 0,  8, 64])

In [15]:
a[:6:2] = -1000
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [16]:
for i in a:
  print(i ** (1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [17]:
# 多维数组
def f(x, y):
    return 10*x + y
a = np.fromfunction(f, (5,4), dtype=int) # 使用函数创建

In [18]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [19]:
a[2,3]

23

In [20]:
a[0:5, 1] # 元组(0:5, 1)

array([ 1, 11, 21, 31, 41])

In [21]:
a[:, 1] # 元组(0:a.shape[0], 1)

array([ 1, 11, 21, 31, 41])

In [22]:
a[1:3, :] # 元组(1:3, 0:a.shape[1])

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [23]:
a[-1] # 比axis数量少的索引, 元组(-1, 0:a.shape[1])

array([40, 41, 42, 43])

In [24]:
a[-1, ...] # 元组(-1, 0:a.shape[1])

array([40, 41, 42, 43])

In [25]:
# ...的用法
a = np.arange(12).reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
a[1, ...] # 移除第一维外的[]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
a[..., 2] # 移除最后一维外的[]

array([[ 2,  5],
       [ 8, 11]])

In [28]:
# 多维数组遍历
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
for row in a: #  按第一维度遍历
    print(row, "\n")

[[0 1 2]
 [3 4 5]] 

[[ 6  7  8]
 [ 9 10 11]] 



In [30]:
for e in a.flat: # 遍历每个元素
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11


## 形状操作

## 拷贝和视图


## 索引

### 索引为数组

In [31]:
# 索引一维数组
a = np.arange(12)**2  
i = np.array( [ 1,1,3,8,5 ] )
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )
a[i], a[j]

(array([ 1,  1,  9, 64, 25]), array([[ 9, 16],
        [81, 49]]))

In [32]:
# 索引二维数组
# When the indexed array a is multidimensional, 
# a single array of indices refers to the first dimension of a.
palette = np.array( [ [0,0,0],                # black
                       [255,0,0],              # red
                       [0,255,0],              # green
                       [0,0,255],              # blue
                       [255,255,255] ] )
image = np.array( [ [ 0, 1, 2, 0 ], 
                   [ 0, 3, 4, 0 ]  ] ) # 参数为单个数组: 每个元组引用a的第一维度
palette[image] # (2,4,3)

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [33]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
i = np.array( [ [0,1],                        # indices for the first dim of a
                 [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                 [3,3] ] )
a[i,j] # 参数为多个数组

array([[ 2,  5],
       [ 7, 11]])

In [35]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [36]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [37]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
i = np.array( [ [0,1], 
               [1,2] ] )
j = np.array( [ [2,1],
               [3,3] ] )
(i, j)

(array([[0, 1],
        [1, 2]]), array([[2, 1],
        [3, 3]]))

In [39]:
s = np.array( [i,j] )
a[s] # 参数为1个数组

IndexError: index 3 is out of bounds for axis 0 with size 3

In [40]:
a[tuple(s)] # 参数为2个数组

array([[ 2,  5],
       [ 7, 11]])

In [41]:
# 所用索引数组赋值
a = np.arange(5)
a[[1,3,4]] = 0
print(a)
a[[0,0,2]]=[1,2,3]
print(a)
a[[0,0,2]]+=1
print(a)

[0 0 2 0 0]
[2 0 3 0 0]
[3 0 4 0 0]


### 索引为布尔数组

In [42]:
# 方式1: 与原始数组形状一样
a = np.arange(12).reshape(3,4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
a[b] # 结果为1维数组

array([ 5,  6,  7,  8,  9, 10, 11])

In [44]:
a[b] = 0 # 赋值
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
# 方式2: 沿着维度选择
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])             # first dim selection
b2 = np.array([True,False,True,False])       # second dim selection

print(a)
print(a[b1,:]) # selecting rows
print(a[b1]) # same thing
print(a[:,b2]) # selecting columns
print(a[b1,b2]) # a weird thing to do

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[ 4 10]


### ix_()

In [46]:
# compute all the a+b*c for all the triplets taken from each of the vectors a, b and c
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
ax,bx,cx = np.ix_(a,b,c)
print("ax={}\nbx={}\ncx={}".format(ax, bx, cx))
print("a.shape={}, b.shape={}, c.shape={}".format(ax.shape, bx.shape, cx.shape))
result = ax+bx*cx
print(result[3,2,4])
print(a[3]+b[2]*c[4])

ax=[[[2]]

 [[3]]

 [[4]]

 [[5]]]
bx=[[[8]
  [5]
  [4]]]
cx=[[[5 4 6 8 3]]]
a.shape=(4, 1, 1), b.shape=(1, 3, 1), c.shape=(1, 1, 5)
17
17


### 索引为字符串

## 线性代数


In [47]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print("a=\n", a)
print("a.transpose()=\n", a.transpose()) # 转置
print("np.linalg.inv(a)=\n", np.linalg.inv(a)) # 矩阵逆

u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
print("eye 2=\n", u) # 单位矩阵

j = np.array([[0.0, -1.0], [1.0, 0.0]])
print("j @ j=\n", j @ j) # 矩阵乘法

print("np.trace(u)=\n", np.trace(u))  # 迹

y = np.array([[5.], [7.]])
print("np.linalg.solve(a, y)=\n", np.linalg.solve(a, y)) # 线性方程组求解

print("np.linalg.eig(j)=\n", np.linalg.eig(j)) # 特征值和特征向量

a=
 [[1. 2.]
 [3. 4.]]
a.transpose()=
 [[1. 3.]
 [2. 4.]]
np.linalg.inv(a)=
 [[-2.   1. ]
 [ 1.5 -0.5]]
eye 2=
 [[1. 0.]
 [0. 1.]]
j @ j=
 [[-1.  0.]
 [ 0. -1.]]
np.trace(u)=
 2.0
np.linalg.solve(a, y)=
 [[-3.]
 [ 4.]]
np.linalg.eig(j)=
 (array([0.+1.j, 0.-1.j]), array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]]))


In [48]:
help(np.linalg.eig)

Help on function eig in module numpy.linalg.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.
    
    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed
    
    Returns
    -------
    w : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs
    
    v : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``v[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``w[i]``.
    
    Raises
    ------
    LinAlgError
        If the eigenvalue computation does not 

## 一些技巧